#!/bin/bash
# Heartbeat Monitor — checks all agent health every 2 hours
# Writes to memory/HEARTBEAT.md and alerts on failures

set -e
cd /Users/josefhofman/Clawdia

DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M)
HEARTBEAT_FILE="memory/HEARTBEAT.md"

# Check key output files freshness
check_freshness() {
    local file="$1"
    local agent="$2"
    local max_hours="$3"

    if [ ! -f "$file" ]; then
        echo "DEAD|$agent|$file|never created"
        return
    fi

    local size=$(wc -c < "$file" | tr -d ' ')
    if [ "$size" -lt 50 ]; then
        echo "EMPTY|$agent|$file|placeholder only (${size}B)"
        return
    fi

    local mod_epoch=$(stat -f %m "$file" 2>/dev/null || stat -c %Y "$file" 2>/dev/null)
    local now_epoch=$(date +%s)
    local diff_hours=$(( (now_epoch - mod_epoch) / 3600 ))

    if [ "$diff_hours" -gt "$max_hours" ]; then
        echo "STALE|$agent|$file|${diff_hours}h old (max ${max_hours}h)"
    else
        echo "OK|$agent|$file|${diff_hours}h old"
    fi
}

# Check all agents
RESULTS=""
RESULTS+="$(check_freshness "knowledge/USER_DIGEST_AM.md" "spojka" 24)\n"
RESULTS+="$(check_freshness "pipedrive/PIPELINE_STATUS.md" "obchodak" 48)\n"
RESULTS+="$(check_freshness "inbox/INBOX_DIGEST.md" "postak" 24)\n"
RESULTS+="$(check_freshness "intel/DAILY-INTEL.md" "strateg" 48)\n"
RESULTS+="$(check_freshness "calendar/TODAY.md" "kalendar" 24)\n"
RESULTS+="$(check_freshness "reviews/SYSTEM_HEALTH.md" "kontrolor" 72)\n"
RESULTS+="$(check_freshness "knowledge/IMPROVEMENTS.md" "archivar" 72)\n"

# Count statuses
OK_COUNT=$(echo -e "$RESULTS" | grep -c "^OK" || true)
STALE_COUNT=$(echo -e "$RESULTS" | grep -c "^STALE" || true)
DEAD_COUNT=$(echo -e "$RESULTS" | grep -c "^DEAD" || true)
EMPTY_COUNT=$(echo -e "$RESULTS" | grep -c "^EMPTY" || true)
TOTAL=$((OK_COUNT + STALE_COUNT + DEAD_COUNT + EMPTY_COUNT))

# Generate heartbeat report
cat > "$HEARTBEAT_FILE" << EOF
# System Heartbeat — $DATE $TIME

## Status: $OK_COUNT/$TOTAL agents healthy

### Healthy (OK)
$(echo -e "$RESULTS" | grep "^OK" | while IFS='|' read status agent file info; do echo "- **$agent** — $info"; done)

### Needs Attention
$(echo -e "$RESULTS" | grep -v "^OK" | grep -v "^$" | while IFS='|' read status agent file info; do [ -n "$agent" ] && echo "- [$status] **$agent** — $info"; done)

## Ollama Status
$(curl -s http://localhost:11434/api/tags 2>/dev/null | python3 -c "import sys,json; models=json.load(sys.stdin).get('models',[]); print(f'{len(models)} model(s) ready: ' + ', '.join(m['name'] for m in models))" 2>/dev/null || echo "Ollama: NOT RUNNING")

## Scheduled Tasks
$(ls -la /Users/josefhofman/.claude/scheduled-tasks/ 2>/dev/null | tail -5 || echo "No scheduled tasks directory")

---
*Auto-generated by heartbeat-check.sh*
EOF

# Alert if too many agents are down
if [ "$OK_COUNT" -lt 3 ]; then
    echo "ALERT: Only $OK_COUNT/$TOTAL agents healthy!" >> logs/orchestrator.log
fi

echo "Heartbeat: $OK_COUNT/$TOTAL healthy, $STALE_COUNT stale, $DEAD_COUNT dead, $EMPTY_COUNT empty"
