#!/usr/bin/env python3
import json
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = ROOT / "control-plane" / "agent-registry.json"
TASKS_OPEN_DIR = ROOT / "tasks" / "open"
TASKS_DONE_DIR = ROOT / "tasks" / "done"
KNOWLEDGE_INSIGHTS = ROOT / "knowledge" / "AGENT_INSIGHTS.md"
TODAY_SUMMARY = ROOT / "knowledge" / "TODAY_SUMMARY.md"
PENDING_REVIEWS = ROOT / "reviews" / "PENDING_REVIEWS.md"


PRIORITY_ORDER = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}
ACTIVE_STATUSES = {"todo", "in_progress", "blocked", "needs_review"}


@dataclass
class Task:
    path: Path
    data: dict

    @property
    def task_id(self) -> str:
        return self.data.get("id", self.path.stem)

    @property
    def title(self) -> str:
        return self.data.get("title", "Untitled task")

    @property
    def owner(self) -> str:
        return self.data.get("owner", "unassigned")

    @property
    def status(self) -> str:
        return self.data.get("status", "todo")

    @property
    def priority(self) -> str:
        return self.data.get("priority", "P3")

    @property
    def due_at(self):
        raw = self.data.get("due_at")
        if not raw:
            return None
        try:
            return datetime.fromisoformat(raw)
        except ValueError:
            return None

    @property
    def updated_at(self):
        raw = self.data.get("updated_at")
        if not raw:
            return None
        try:
            return datetime.fromisoformat(raw)
        except ValueError:
            return None


def load_json(path: Path):
    return json.loads(path.read_text())


def load_registry():
    return load_json(REGISTRY_PATH)


def load_tasks(directory: Path):
    tasks = []
    if not directory.exists():
        return tasks
    for path in sorted(directory.glob("*.json")):
        tasks.append(Task(path=path, data=load_json(path)))
    return tasks


def format_dt(value):
    if not value:
        return "n/a"
    return value.isoformat(timespec="minutes")


def sort_tasks(tasks):
    return sorted(
        tasks,
        key=lambda task: (
            PRIORITY_ORDER.get(task.priority, 99),
            task.due_at or datetime.max.replace(tzinfo=timezone.utc),
            task.task_id,
        ),
    )


def summarize_agent_outputs(outputs):
    lines = []
    for output in outputs:
        path = ROOT / output
        if path.exists():
            mtime = datetime.fromtimestamp(path.stat().st_mtime).astimezone()
            lines.append(f"- `{output}` updated {format_dt(mtime)}")
        else:
            lines.append(f"- `{output}` missing")
    return lines


def write_agent_insights(registry, open_tasks, done_tasks):
    now = datetime.now().astimezone()
    by_owner = defaultdict(list)
    for task in open_tasks:
        by_owner[task.owner].append(task)

    lines = [
        "# AGENT_INSIGHTS",
        "",
        f"Generated by `scripts/knowledge_sync.py` at {format_dt(now)}.",
        "",
        "## System Snapshot",
        f"- Open tasks: {len(open_tasks)}",
        f"- Completed tasks archived: {len(done_tasks)}",
        f"- Blocked tasks: {sum(1 for task in open_tasks if task.status == 'blocked')}",
        f"- Tasks awaiting review: {sum(1 for task in open_tasks if task.status == 'needs_review')}",
        "",
    ]

    for agent_id, meta in registry["agents"].items():
        if agent_id == registry["main_agent"]:
            continue
        tasks = sort_tasks(by_owner.get(agent_id, []))
        display_name = meta["display_name"]
        lines.append(f"## {display_name}")
        lines.append(f"- Agent id: `{agent_id}`")
        lines.append(f"- Active tasks: {len(tasks)}")
        if tasks:
            lines.append(
                "- Top tasks: "
                + ", ".join(f"`{task.task_id}` ({task.status}, {task.priority})" for task in tasks[:3])
            )
        else:
            lines.append("- Top tasks: none")
        lines.extend(summarize_agent_outputs(meta.get("writes_to", []))[:2])
        lines.append("")

    KNOWLEDGE_INSIGHTS.write_text("\n".join(lines).rstrip() + "\n")


def write_today_summary(open_tasks):
    now = datetime.now().astimezone()
    active = sort_tasks([task for task in open_tasks if task.status in ACTIVE_STATUSES])
    blocked = [task for task in active if task.status == "blocked"]
    due_soon = [task for task in active if task.due_at][:5]

    lines = [
        "# TODAY_SUMMARY",
        "",
        f"Generated by `scripts/knowledge_sync.py` at {format_dt(now)}.",
        "",
        "## Priorities",
    ]
    if active:
        for task in active[:5]:
            lines.append(
                f"- `{task.task_id}` `{task.priority}` `{task.owner}` due {format_dt(task.due_at)}: {task.title}"
            )
    else:
        lines.append("- No open tasks.")

    lines.extend(["", "## Blockers"])
    if blocked:
        for task in blocked:
            blocker_text = ", ".join(task.data.get("blockers", [])) or "unspecified blocker"
            lines.append(f"- `{task.task_id}` `{task.owner}`: {blocker_text}")
    else:
        lines.append("- No blocked tasks.")

    lines.extend(["", "## Next Deadlines"])
    if due_soon:
        for task in due_soon:
            lines.append(f"- `{task.task_id}` due {format_dt(task.due_at)}")
    else:
        lines.append("- No dated tasks.")

    TODAY_SUMMARY.write_text("\n".join(lines).rstrip() + "\n")


def write_pending_reviews(open_tasks):
    review_tasks = sort_tasks([task for task in open_tasks if task.status in {"blocked", "needs_review"}])
    now = datetime.now().astimezone()
    lines = [
        "# PENDING_REVIEWS",
        "",
        f"Generated by `scripts/knowledge_sync.py` at {format_dt(now)}.",
        "",
    ]
    if review_tasks:
        for task in review_tasks:
            reviewer = task.data.get("reviewer", "reviewer")
            lines.append(
                f"- `{task.task_id}` owned by `{task.owner}` status `{task.status}` reviewer `{reviewer}`"
            )
    else:
        lines.append("- No pending reviews.")
    PENDING_REVIEWS.write_text("\n".join(lines).rstrip() + "\n")


def main():
    registry = load_registry()
    open_tasks = load_tasks(TASKS_OPEN_DIR)
    done_tasks = load_tasks(TASKS_DONE_DIR)
    write_agent_insights(registry, open_tasks, done_tasks)
    write_today_summary(open_tasks)
    write_pending_reviews(open_tasks)


if __name__ == "__main__":
    main()
