#!/usr/bin/env python3
"""
Reviewer Recovery — generates a fresh reviews/SYSTEM_HEALTH.md
Runs real health checks: file ages, disk space, process status, agent outputs.
Runs standalone: python3 scripts/recover_reviewer.py
"""

import json
import os
import shutil
import subprocess
import time
from datetime import datetime
from pathlib import Path

BASE = Path("/Users/josefhofman/Clawdia")
OUTPUT = BASE / "reviews" / "SYSTEM_HEALTH.md"
RECOVERY_LOG = BASE / "logs" / "recovery.log"

# Same agent definitions as orchestrator
AGENT_FILES = {
    "spojka": "knowledge/USER_DIGEST_AM.md",
    "obchodak": "pipedrive/PIPELINE_STATUS.md",
    "postak": "inbox/INBOX_DIGEST.md",
    "strateg": "intel/DAILY-INTEL.md",
    "kalendar": "calendar/TODAY.md",
    "kontrolor": "reviews/SYSTEM_HEALTH.md",
    "archivar": "knowledge/IMPROVEMENTS.md",
}

MAX_HOURS = {
    "spojka": 24, "obchodak": 48, "postak": 24,
    "strateg": 48, "kalendar": 24, "kontrolor": 72,
    "archivar": 72,
}


def log_recovery(msg):
    RECOVERY_LOG.parent.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(RECOVERY_LOG, "a") as f:
        f.write(f"[{ts}] [recover_reviewer] {msg}\n")


def check_agent_outputs():
    """Check all agent output files, return status list"""
    now = time.time()
    results = []
    for agent, filepath in AGENT_FILES.items():
        path = BASE / filepath
        max_h = MAX_HOURS.get(agent, 48)

        if not path.exists():
            results.append((agent, "DEAD", "file missing", filepath))
        elif path.stat().st_size < 50:
            results.append((agent, "EMPTY", f"placeholder ({path.stat().st_size}B)", filepath))
        else:
            age_h = (now - path.stat().st_mtime) / 3600
            if age_h > max_h:
                results.append((agent, "STALE", f"{int(age_h)}h old (max {max_h}h)", filepath))
            else:
                results.append((agent, "OK", f"{int(age_h)}h old", filepath))
    return results


def check_disk_space():
    """Get disk usage for Clawdia directory and overall"""
    try:
        usage = shutil.disk_usage(str(BASE))
        total_gb = usage.total / (1024 ** 3)
        free_gb = usage.free / (1024 ** 3)
        used_pct = (usage.used / usage.total) * 100
        return {
            "total_gb": round(total_gb, 1),
            "free_gb": round(free_gb, 1),
            "used_pct": round(used_pct, 1),
        }
    except Exception:
        return None


def check_clawdia_dir_size():
    """Get total size of Clawdia directory"""
    try:
        result = subprocess.run(
            ["du", "-sh", str(BASE)],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0:
            return result.stdout.strip().split("\t")[0]
    except Exception:
        pass
    return "unknown"


def check_ollama():
    """Check if Ollama is running"""
    try:
        result = subprocess.run(
            ["curl", "-s", "-m", "3", "http://localhost:11434/api/tags"],
            capture_output=True, text=True, timeout=5,
        )
        if result.returncode == 0:
            data = json.loads(result.stdout)
            models = [m.get("name", "?") for m in data.get("models", [])]
            return True, models
    except Exception:
        pass
    return False, []


def check_orchestrator_pid():
    """Check if orchestrator is running"""
    pid_file = BASE / "logs" / "orchestrator.pid"
    if pid_file.exists():
        try:
            pid = int(pid_file.read_text().strip())
            # Check if process is alive
            os.kill(pid, 0)
            return True, pid
        except (ValueError, ProcessLookupError, PermissionError):
            return False, None
    return False, None


def check_log_sizes():
    """Check log file sizes"""
    logs_dir = BASE / "logs"
    if not logs_dir.exists():
        return []
    results = []
    for logfile in sorted(logs_dir.glob("*.log")) + sorted(logs_dir.glob("*.jsonl")):
        size_kb = logfile.stat().st_size / 1024
        results.append((logfile.name, round(size_kb, 1)))
    return results


def check_recent_recovery():
    """Check recent recovery activity"""
    if RECOVERY_LOG.exists():
        lines = RECOVERY_LOG.read_text().strip().splitlines()
        return lines[-5:] if lines else []
    return []


def generate_health_report():
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d %H:%M")

    sections = []
    sections.append(f"# System Health Report — {date_str}")
    sections.append(f"\n> Auto-generated by Reviewer recovery\n")

    # Agent health table
    agents = check_agent_outputs()
    ok_count = sum(1 for _, status, _, _ in agents if status == "OK")
    total = len(agents)

    sections.append(f"## Agent Health ({ok_count}/{total} healthy)\n")
    sections.append("| Agent | Status | Details | File |")
    sections.append("|-------|--------|---------|------|")
    for agent, status, detail, filepath in agents:
        icon = {"OK": "OK", "STALE": "STALE", "DEAD": "DEAD", "EMPTY": "EMPTY"}.get(status, "?")
        sections.append(f"| {agent} | **{icon}** | {detail} | `{filepath}` |")

    # Orchestrator status
    sections.append("\n## Orchestrator")
    orch_running, orch_pid = check_orchestrator_pid()
    if orch_running:
        sections.append(f"- Status: **RUNNING** (PID {orch_pid})")
    else:
        sections.append("- Status: **NOT RUNNING**")

    # Ollama status
    sections.append("\n## Ollama (Local LLM)")
    ollama_ok, models = check_ollama()
    if ollama_ok:
        sections.append(f"- Status: **ONLINE**")
        sections.append(f"- Models: {', '.join(models) if models else 'none loaded'}")
    else:
        sections.append("- Status: **OFFLINE**")

    # Disk
    sections.append("\n## Disk")
    disk = check_disk_space()
    if disk:
        sections.append(f"- System: {disk['used_pct']}% used, {disk['free_gb']}GB free of {disk['total_gb']}GB")
    clawdia_size = check_clawdia_dir_size()
    sections.append(f"- Clawdia directory: {clawdia_size}")

    # Log sizes
    sections.append("\n## Log Files")
    logs = check_log_sizes()
    if logs:
        for name, size_kb in logs:
            flag = " **[LARGE]**" if size_kb > 500 else ""
            sections.append(f"- `{name}`: {size_kb}KB{flag}")
    else:
        sections.append("- No log files found")

    # Recent recovery
    sections.append("\n## Recent Recovery Activity")
    recent = check_recent_recovery()
    if recent:
        for line in recent:
            sections.append(f"- {line}")
    else:
        sections.append("- No recent recovery activity")

    # Recommendations
    sections.append("\n## Recommendations")
    recs = []
    stale_agents = [a for a, s, _, _ in agents if s in ("STALE", "DEAD", "EMPTY")]
    if stale_agents:
        recs.append(f"- Fix stale agents: {', '.join(stale_agents)}")
    if not orch_running:
        recs.append("- Restart orchestrator: `launchctl kickstart -k gui/$(id -u)/com.clawdia.orchestrator`")
    if not ollama_ok:
        recs.append("- Start Ollama: `ollama serve`")
    if disk and disk["free_gb"] < 5:
        recs.append(f"- Low disk space: only {disk['free_gb']}GB free")
    large_logs = [n for n, s in logs if s > 500]
    if large_logs:
        recs.append(f"- Large log files to rotate: {', '.join(large_logs)}")
    if not recs:
        recs.append("- System looks healthy. No immediate action needed.")
    sections.extend(recs)

    sections.append(f"\n---\n*Recovery timestamp: {now.isoformat()}*")

    return "\n".join(sections)


def main():
    try:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        content = generate_health_report()
        OUTPUT.write_text(content)
        log_recovery(f"SUCCESS — wrote {len(content)}B to {OUTPUT}")
        print(f"OK: SYSTEM_HEALTH.md updated ({len(content)}B)")
        return 0
    except Exception as e:
        log_recovery(f"FAILED — {e}")
        print(f"ERROR: {e}", flush=True)
        return 1


if __name__ == "__main__":
    exit(main())
