#!/usr/bin/env python3
"""
InboxForge Recovery — generates a fresh INBOX_DIGEST.md
Runs standalone: python3 scripts/recover_inbox.py
"""

import os
import json
import subprocess
from datetime import datetime
from pathlib import Path

BASE = Path("/Users/josefhofman/Clawdia")
OUTPUT = BASE / "inbox" / "INBOX_DIGEST.md"
RECOVERY_LOG = BASE / "logs" / "recovery.log"


def log_recovery(msg):
    RECOVERY_LOG.parent.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(RECOVERY_LOG, "a") as f:
        f.write(f"[{ts}] [recover_inbox] {msg}\n")


def get_recent_drafts():
    """Check inbox/DRAFTS.md and inbox/FOLLOW_UPS.md for context"""
    items = []
    for fname in ["DRAFTS.md", "FOLLOW_UPS.md"]:
        p = BASE / "inbox" / fname
        if p.exists() and p.stat().st_size > 50:
            items.append(f"- `{fname}`: {p.stat().st_size}B, last updated {datetime.fromtimestamp(p.stat().st_mtime).strftime('%Y-%m-%d %H:%M')}")
    return items


def get_pipeline_summary():
    """Pull quick stats from pipeline if available"""
    pipeline = BASE / "pipedrive" / "PIPELINE_STATUS.md"
    if pipeline.exists() and pipeline.stat().st_size > 100:
        content = pipeline.read_text()
        lines = [l.strip() for l in content.splitlines() if l.strip() and not l.startswith("#")]
        return lines[:5]
    return []


def get_approval_queue_count():
    """Count pending approvals"""
    pending = BASE / "approval-queue" / "pending"
    if pending.exists():
        return len(list(pending.glob("*.json")) + list(pending.glob("*.md")))
    return 0


def generate_digest():
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M")

    sections = []

    # Header
    sections.append(f"# Inbox Digest — {date_str}")
    sections.append(f"\n> Auto-generated by recovery at {time_str}. InboxForge agent was stale.\n")

    # Inbox file status
    sections.append("## Inbox Status")
    drafts_info = get_recent_drafts()
    if drafts_info:
        sections.append("\n".join(drafts_info))
    else:
        sections.append("- No active drafts or follow-ups detected")

    # Approval queue
    pending_count = get_approval_queue_count()
    sections.append(f"\n## Approval Queue\n- **{pending_count}** items pending approval")

    # Pipeline context
    pipeline_lines = get_pipeline_summary()
    if pipeline_lines:
        sections.append("\n## Pipeline Context (from last scoring)")
        for line in pipeline_lines:
            sections.append(f"- {line}")

    # Action items
    sections.append("\n## Action Items")
    sections.append("- [ ] Review any pending email drafts in `inbox/DRAFTS.md`")
    sections.append("- [ ] Check follow-ups in `inbox/FOLLOW_UPS.md`")
    if pending_count > 0:
        sections.append(f"- [ ] Process {pending_count} pending approvals")

    sections.append(f"\n---\n*Recovery timestamp: {now.isoformat()}*")

    return "\n".join(sections)


def main():
    try:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        content = generate_digest()
        OUTPUT.write_text(content)
        log_recovery(f"SUCCESS — wrote {len(content)}B to {OUTPUT}")
        print(f"OK: INBOX_DIGEST.md updated ({len(content)}B)")
        return 0
    except Exception as e:
        log_recovery(f"FAILED — {e}")
        print(f"ERROR: {e}", flush=True)
        return 1


if __name__ == "__main__":
    exit(main())
