#!/usr/bin/env bash
set -euo pipefail
TZ="Europe/Prague"
openclaw cron create --name growthlab-morning --agent main --cron "30 6 * * *" --tz "$TZ" --message "[GrowthLab] Proveď ranní research a aktualizuj intel/DAILY-INTEL.md"
openclaw cron create --name timebox-briefing --agent main --cron "0 7 * * *" --tz "$TZ" --message "[Timebox] Připrav calendar/TODAY.md a prep notes"
openclaw cron create --name dealops-am --agent main --cron "15 7 * * *" --tz "$TZ" --message "[DealOps] Ranní pipeline check + hygiene report"
openclaw cron create --name inboxforge-am --agent main --cron "30 7 * * *" --tz "$TZ" --message "[InboxForge] Ranní inbox triage + drafty"
openclaw cron create --name bridge-am-report --agent main --cron "0 8 * * *" --tz "$TZ" --message "[Bridge] Ranní report Josefovi"
openclaw cron create --name growthlab-noon --agent main --cron "0 12 * * *" --tz "$TZ" --message "[GrowthLab] Polední intel update"
openclaw cron create --name dealops-noon --agent main --cron "30 12 * * *" --tz "$TZ" --message "[DealOps] Midday pipeline check"
openclaw cron create --name inboxforge-noon --agent main --cron "0 13 * * *" --tz "$TZ" --message "[InboxForge] Polední inbox check"
openclaw cron create --name dealops-pm --agent main --cron "0 17 * * *" --tz "$TZ" --message "[DealOps] PM pipeline report"
openclaw cron create --name inboxforge-pm --agent main --cron "15 17 * * *" --tz "$TZ" --message "[InboxForge] PM inbox sweep"
openclaw cron create --name reviewer-pm --agent main --cron "30 17 * * *" --tz "$TZ" --message "[Reviewer] System health check"
openclaw cron create --name knowledgekeeper-sync --agent main --cron "0 18 * * *" --tz "$TZ" --message "[KnowledgeKeeper] Daily knowledge sync"
openclaw cron create --name bridge-pm-report --agent main --cron "30 18 * * *" --tz "$TZ" --message "[Bridge] Večerní report Josefovi"
openclaw cron create --name knowledgekeeper-night --agent main --cron "0 22 * * *" --tz "$TZ" --message "[KnowledgeKeeper] Night archive + dedupe"
openclaw cron create --name reviewer-night --agent main --cron "30 22 * * *" --tz "$TZ" --message "[Reviewer] Night security check"
echo "Agent Army cron setup complete"
